name: SmashsBuild
version: 1.0
description: Plugin pour le serveur build
author: Skyzen
authors: [farzim]
website: http://www.smashs.net/

commands:
  sb-objectif:
    description: Reload le plugin SmashsBuild
    aliases: [sbj, sbobj, sb-obj]

main: com.skyzen.smashsgames.Main