name: SmashsBuild
version: 1.0
description: Plugin pour le serveur build
author: Skyzen
authors: [farzim]
website: http://www.smashs.net/

commands:
  sb-objectif:
    description: Modifier l'objectif de construction
    aliases: [sbj, sbobj, sb-obj]

main: com.skyzen.smashsgames.Main