name: SmashsBuild
version: 1.0
description: Plugin pour le serveur build
author: Skyzen
authors: [farzim]
website: http://www.smashs.net/

commands:
  sb-objectif:
    description: Modifier l'objectif de construction
    aliases: [sbj, sbobj, sb-obj]
  spawn:
    description: Retourner au spawn
    aliases: [s]
  setwarp:
    description: Créer un warp
    aliases: [sw]
  warp:
    description: Se téléporter à un warp
    aliases: [w]
  delwarp:
    description: Supprimer un warp
    aliases: [dw]

main: com.skyzen.smashsgames.Main