name: SmashsBuild
version: 1.0
description: Plugin pour le serveur build
author: Skyzen
authors: [farzim]
website: http://www.smashs.net/

commands:
  sb-reload:
    description: Reload le plugin SmashsBuild
    aliases: [sbr, sbrl]

main: com.skyzen.smashsgames.Main